name: pgkb-dev
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.0.2
  - python=3.8.2
  - readline=8.0
  - setuptools=46.2.0
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - attrs==19.3.0
    - colorama==0.4.3
    - docopt==0.6.2
    - more-itertools==8.2.0
    - numpy==1.18.4
    - packaging==20.3
    - pandas==1.0.3
    - pathtools==0.1.2
    - pluggy==0.13.1
    - py==1.8.1
    - pyparsing==2.4.7
    - pytest==5.4.2
    - pytest-watch==4.2.0
    - python-dateutil==2.8.1
    - pytz==2020.1
    - six==1.14.0
    - watchdog==0.10.2
    - wcwidth==0.1.9
    - xlrd==1.2.0

